"use client";
import { useCallback,useMemo,useState } from "react";
import { Eye,Play,RotateCcw,Waves } from "lucide-react";
import {Feedback,MathRange,PhaseOneVisualProof,Toggle,ToolButton,svgPoint,useRafAnimation} from "../../../components/phase-one/PhaseOneVisualProof";
import {proofConfig} from "./proof.config";
const W=900,H=560,cx=205,cy=285,r=145,PI=Math.PI;
const xy=(t:number)=>({x:cx+r*Math.cos(t),y:cy-r*Math.sin(t)});
const path=(fn:(x:number)=>number,y0:number)=>Array.from({length:181},(_,i)=>{const t=i*2*PI/180;return `${i?"L":"M"} ${430+t/(2*PI)*430} ${y0-82*fn(t)}`}).join(" ");
const shown=(value:number)=>Math.abs(value)<.0005?"0.000":value.toFixed(3);
export default function Proof(){
 const [theta,setTheta]=useState(PI/3),[drag,setDrag]=useState(false),[traceSin,setTraceSin]=useState(true),[traceCos,setTraceCos]=useState(true),[projections,setProjections]=useState(true),[speed,setSpeed]=useState(1),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<"idle"|"correct"|"wrong">("idle"),[active,setActive]=useState(-1);
 const p=useMemo(()=>xy(theta),[theta]); const s=Math.sin(theta),c=Math.cos(theta);
 const frame=useCallback((q:number)=>{setTheta(q*2*PI);setActive(Math.min(3,Math.floor(q*4)));},[]); const anim=useRafAnimation(frame);
 const pointer=(e:React.PointerEvent<SVGSVGElement>)=>{if(!drag)return;const q=svgPoint(e,{width:W,height:H});let a=Math.atan2(cy-q.y,q.x-cx);if(a<0)a+=2*PI;setTheta(a)};
 const reset=()=>{anim.stop();setTheta(PI/3);setTraceSin(true);setTraceCos(true);setProjections(true);setAnswer("");setFeedback("idle");setActive(-1)};
 return <PhaseOneVisualProof meta={proofConfig} activeStep={active} steps={[
  {title:"Rotate on the circle",body:<>P=(cos θ, sin θ) moves through one revolution.</>},{title:"Project the coordinates",body:"The height is sine; the horizontal coordinate is cosine."},{title:"Carry values to the graphs",body:"The same angle becomes horizontal position on both graphs."},{title:"See periodic waves",body:"After 2π, the point and both values repeat."}
 ]} tools={<><ToolButton title="Advance angle" subtitle="Rotate 15°, or drag the point" onClick={()=>setTheta(v=>(v+PI/12)%(2*PI))} icon={<RotateCcw size={18}/>}/><ToolButton title="Show projections" subtitle="Connect circle coordinates to values" active={projections} onClick={()=>setProjections(v=>!v)} icon={<Eye size={18}/>}/><ToolButton title="Trace sine" subtitle="Show y = sin θ" active={traceSin} onClick={()=>setTraceSin(v=>!v)} icon={<Waves size={18}/>}/><ToolButton title="Trace cosine" subtitle="Show y = cos θ" active={traceCos} onClick={()=>setTraceCos(v=>!v)} icon={<Waves size={18}/>}/><ToolButton title="Reset" subtitle="Return to θ = π/3" onClick={reset}/><ToolButton title={anim.playing?"Pause cycle":"Animate cycle"} subtitle="Watch one complete revolution" active={anim.playing} onClick={()=>anim.playing?anim.stop():anim.start(6200/speed)} icon={<Play size={18}/>}/><MathRange label="Speed" value={speed} min={0.5} max={2} step={0.5} onChange={setSpeed} display={`${speed}×`}/></>} result={<><h2>Circular motion creates waves</h2><p>The point’s y-coordinate traces sine, while its x-coordinate traces cosine.</p></>} challenge={<><p>At θ = 3π/2, what is sin θ?</p><div style={{display:"flex",gap:8}}><input value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback("idle")}} aria-label="sine answer"/><button onClick={()=>setFeedback(Number(answer)===-1?"correct":"wrong")}>Check</button></div><Feedback state={feedback}/></>}>
  <MathRange label="Angle θ" value={theta} min={0} max={2*PI} step={0.005} onChange={setTheta} display={`${(theta*180/PI).toFixed(1)}° · ${(theta/PI).toFixed(2)}π`}/>
  <svg className="phaseOneCanvas" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Unit circle linked to sine and cosine graphs" onPointerMove={pointer} onPointerUp={()=>setDrag(false)} onPointerLeave={()=>setDrag(false)}>
   <line className="axis" x1="35" y1={cy} x2="375" y2={cy}/><line className="axis" x1={cx} y1="90" x2={cx} y2="480"/><circle cx={cx} cy={cy} r={r} fill="none" stroke="#6537f0" strokeWidth="2.5"/><line x1={cx} y1={cy} x2={p.x} y2={p.y} stroke="#5d31ef" strokeWidth="4"/>
   {projections&&<><line x1={p.x} y1={p.y} x2={p.x} y2={cy} stroke="#079b8e" strokeWidth="3" strokeDasharray="6 4"/><line x1={cx} y1={cy} x2={p.x} y2={cy} stroke="#ef4838" strokeWidth="3"/><path d={`M ${p.x} ${p.y} C 360 ${p.y},390 ${158-82*s},430 ${158-82*s}`} fill="none" stroke="#079b8e" strokeDasharray="7 5"/><path d={`M ${p.x} ${cy} C 365 ${cy},390 ${408-82*c},430 ${408-82*c}`} fill="none" stroke="#ef4838" strokeDasharray="7 5"/></>}
   <circle className="purple handle" cx={p.x} cy={p.y} r="10" tabIndex={0} role="slider" aria-label="angle" aria-valuenow={Math.round(theta*180/PI)} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag(true)}} onKeyDown={e=>{if(e.key==="ArrowRight")setTheta(v=>Math.min(2*PI,v+.03));if(e.key==="ArrowLeft")setTheta(v=>Math.max(0,v-.03))}}/>
   <text x="55" y="62" fill="#07865b" fontWeight="700">sin θ = {shown(s)}</text><text x="55" y="84" fill="#e63e2e" fontWeight="700">cos θ = {shown(c)}</text>
   {[158,408].map(y=><g key={y}><rect x="410" y={y-112} width="465" height="205" rx="13" fill="#fbfcff" stroke="#dce0ef"/><line className="axis" x1="430" y1={y} x2="860" y2={y}/><line className="axis" x1="430" y1={y-95} x2="430" y2={y+90}/>{[0,.5,1,1.5,2].map(q=><g key={q}><line className="gridLine" x1={430+q*215} y1={y-95} x2={430+q*215} y2={y+90}/><text x={430+q*215} y={y+19} textAnchor="middle" fontSize="11">{q===0?"0":q===.5?"π/2":q===1?"π":q===1.5?"3π/2":"2π"}</text></g>)}</g>)}
   <text x="435" y="66" fill="#07865b" fontWeight="700">Sine graph: y = sin θ</text><text x="435" y="316" fill="#e63e2e" fontWeight="700">Cosine graph: y = cos θ</text>
   {traceSin&&<path d={path(Math.sin,158)} fill="none" stroke="#079b62" strokeWidth="3"/>}{traceCos&&<path d={path(Math.cos,408)} fill="none" stroke="#ef4838" strokeWidth="3"/>}
   <line x1={430+theta/(2*PI)*430} y1="46" x2={430+theta/(2*PI)*430} y2="498" stroke="#805bf4" strokeWidth="2" strokeDasharray="5 4"/><circle cx={430+theta/(2*PI)*430} cy={158-82*s} r="7" fill="#079b62"/><circle cx={430+theta/(2*PI)*430} cy={408-82*c} r="7" fill="#ef4838"/>
  </svg>
  <div style={{display:"flex",gap:18,flexWrap:"wrap",padding:"2px 8px"}}><Toggle label="Projections" checked={projections} onChange={setProjections}/><Toggle label="Sine trace" checked={traceSin} onChange={setTraceSin}/><Toggle label="Cosine trace" checked={traceCos} onChange={setTraceCos}/></div>
 </PhaseOneVisualProof>
}
