"use client";
import {useCallback,useMemo,useState} from "react";
import {Eye,Play,Shapes} from "lucide-react";
import {Feedback,MathRange,PhaseOneVisualProof,ResetTool,Toggle,ToolButton,useRafAnimation} from "../../../components/phase-one/PhaseOneVisualProof";
import {proofConfig} from "./proof.config";
const W=900,H=560,cx=440,cy=285,r=220,PI=Math.PI;
export default function Proof(){
 const [n,setN]=useState(6),[rotation,setRotation]=useState(0),[polygon,setPolygon]=useState(true),[radials,setRadials]=useState(true),[labels,setLabels]=useState(true),[argumentsOn,setArguments]=useState(true),[reveal,setReveal]=useState(1),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<"idle"|"correct"|"wrong">("idle");
 const roots=useMemo(()=>Array.from({length:n},(_,k)=>{const a=rotation+2*PI*k/n;return{k,a,x:cx+r*Math.cos(a),y:cy-r*Math.sin(a)}}),[n,rotation]);
 const frame=useCallback((p:number)=>setReveal(p),[]),anim=useRafAnimation(frame); const visible=Math.max(1,Math.ceil(reveal*n)); const active=Math.min(3,Math.floor(reveal*4));
 const reset=()=>{anim.stop();setN(6);setRotation(0);setPolygon(true);setRadials(true);setLabels(true);setArguments(true);setReveal(1);setAnswer("");setFeedback("idle")};
 const setCount=(v:number)=>{setN(v);setReveal(1);setFeedback("idle")}; const points=roots.slice(0,visible).map(q=>`${q.x},${q.y}`).join(" ");
 return <PhaseOneVisualProof meta={proofConfig} activeStep={active} steps={[
  {title:"Solve zⁿ = 1",body:<>The solutions are zₖ = e^(2πik/n).</>},{title:"Keep modulus 1",body:"Every root lies on the complex unit circle."},{title:"Add equal arguments",body:<>Each new root advances by 2π/n.</>},{title:"Connect the roots",body:"Equal spacing creates a regular n-gon with rotational symmetry."}
 ]} tools={<><ToolButton title="Increase n" subtitle="Add one root, wrapping after 24" onClick={()=>setCount(n===24?2:n+1)} icon={<Shapes size={18}/>}/><ToolButton title="Show polygon" subtitle="Connect consecutive roots" active={polygon} onClick={()=>setPolygon(v=>!v)} icon={<Shapes size={18}/>}/><ToolButton title="Show radial lines" subtitle="Reveal equal central angles" active={radials} onClick={()=>setRadials(v=>!v)} icon={<Eye size={18}/>}/><ToolButton title="Show labels" subtitle="Display root indices and values" active={labels} onClick={()=>setLabels(v=>!v)} icon={<Eye size={18}/>}/><ToolButton title="Show arguments" subtitle="Display the 2πk/n angles" active={argumentsOn} onClick={()=>setArguments(v=>!v)} icon={<Eye size={18}/>}/><ResetTool onClick={reset}/><ToolButton title={anim.playing?"Pause construction":"Animate construction"} subtitle="Place the roots one equal turn at a time" active={anim.playing} onClick={()=>anim.playing?anim.stop():(setReveal(0),anim.start(4500))} icon={<Play size={18}/>}/></>} result={<><h2>The n-th roots are vertices of a regular n-gon</h2><p>{rotation<.001?"Each point solves zⁿ=1; all have modulus 1 and spacing 2π/n.":"This rotated copy keeps modulus 1 and spacing 2π/n, but generally its points no longer solve zⁿ=1."}</p></>} challenge={<><p>For n = {n}, what is the angle in degrees between adjacent roots?</p><div style={{display:"flex",gap:8}}><input value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback("idle")}} inputMode="decimal" aria-label="angle between roots"/><button onClick={()=>setFeedback(Math.abs(Number(answer)-360/n)<.02?"correct":"wrong")}>Check</button></div><Feedback state={feedback}/></>}>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><MathRange label="Number of roots n" value={n} min={2} max={24} onChange={setCount}/><MathRange label="Global rotation φ" value={rotation} min={0} max={2*PI} step={.01} onChange={setRotation} display={`${(rotation*180/PI).toFixed(0)}°`}/></div>
  <svg className="phaseOneCanvas" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={rotation<.001?`${n} roots of unity on the complex plane`:`Rotated copy of ${n} equally spaced unit-circle points`}>
   <line className="axis" x1="165" y1={cy} x2="715" y2={cy}/><line className="axis" x1={cx} y1="25" x2={cx} y2="535"/><text x="722" y={cy-9}>Re(z)</text><text x={cx+10} y="31">Im(z)</text><circle cx={cx} cy={cy} r={r} fill="rgba(101,55,240,.025)" stroke="#6537f0" strokeWidth="2.5"/>
   {radials&&roots.slice(0,visible).map(q=><line key={q.k} x1={cx} y1={cy} x2={q.x} y2={q.y} stroke="#8a69f4" strokeWidth="1.5" strokeDasharray="6 5"/>)}
   {polygon&&visible>1&&<polyline points={visible===n?`${points} ${roots[0].x},${roots[0].y}`:points} fill={visible===n?"rgba(110,70,240,.10)":"none"} stroke="#6537f0" strokeWidth="2.5"/>}
   {roots.slice(0,visible).map((q,i)=><g key={q.k}><circle aria-label={`k=${q.k}; angle=${(q.a*180/PI).toFixed(1)}°; (${Math.cos(q.a).toFixed(3)}, ${Math.sin(q.a).toFixed(3)})`} cx={q.x} cy={q.y} r="9" fill={`hsl(${(i*300/n+8)%360} 78% 51%)`} stroke="#fff" strokeWidth="3"></circle>{labels&&n<=12&&<text x={q.x+15*Math.cos(q.a)} y={q.y-15*Math.sin(q.a)} textAnchor={Math.cos(q.a)<-.2?"end":"start"} className="mathText" fontWeight="700">ω^{q.k}</text>}{argumentsOn&&n<=8&&<text x={cx+(r+47)*Math.cos(q.a)} y={cy-(r+47)*Math.sin(q.a)} textAnchor="middle" fontSize="11">{rotation<.001?`e^(${q.k===0?"0":`2πi·${q.k}/${n}`})`:`e^(iφ + 2πi·${q.k}/${n})`}</text>}</g>)}
   <path d={`M ${cx+70} ${cy} A 70 70 0 0 0 ${cx+70*Math.cos(2*PI/n)} ${cy-70*Math.sin(2*PI/n)}`} fill="none" stroke="#6b44eb" strokeWidth="3"/><text x={cx+88*Math.cos(PI/n)} y={cy-88*Math.sin(PI/n)} textAnchor="middle" className="mathText">2π/n</text>
   <rect x="20" y="45" width="205" height="160" rx="14" fill="#fbfcff" stroke="#dce0ef"/><text x="122" y="78" textAnchor="middle" fontWeight="700">Angle between roots</text><text x="122" y="116" textAnchor="middle" className="mathText" fontSize="25">2π / {n}</text><text x="122" y="146" textAnchor="middle">= {(2*PI/n).toFixed(3)} rad</text><text x="122" y="174" textAnchor="middle">= {(360/n).toFixed(2)}°</text>
   <rect x="690" y="55" width="190" height="160" rx="14" fill="#f4f1ff" stroke="#d2caf8"/><text x="785" y="87" textAnchor="middle" fontWeight="700">General form</text><text x="785" y="128" textAnchor="middle" className="mathText" fontSize="24">zₖ = e^(2πik/n)</text><text x="785" y="160" textAnchor="middle">k = 0, 1, …, {n-1}</text><text x="785" y="185" textAnchor="middle">|zₖ| = 1</text>{rotation>=.001&&<text x="785" y="205" textAnchor="middle" fontSize="10" fill="#6653bc">Rotated copy: e^(iφ)zₖ</text>}
  </svg>
  <div style={{display:"flex",gap:16,flexWrap:"wrap",padding:"2px 8px"}}><Toggle label="Polygon" checked={polygon} onChange={setPolygon}/><Toggle label="Radial lines" checked={radials} onChange={setRadials}/><Toggle label="Labels" checked={labels} onChange={setLabels}/><Toggle label="Arguments" checked={argumentsOn} onChange={setArguments}/></div>
 </PhaseOneVisualProof>
}
