"use client";
import {useCallback,useMemo,useState} from "react";
import {Eye,Move,Play} from "lucide-react";
import {Feedback,PhaseOneVisualProof,ResetTool,Toggle,ToolButton,svgPoint,useRafAnimation} from "../../../components/phase-one/PhaseOneVisualProof";
import {proofConfig} from "./proof.config";
type C={x:number;y:number}; const W=900,H=560,cx=475,cy=285,scale=98;
const clamp=(n:number)=>Math.max(-2.25,Math.min(2.25,n)); const mag=(z:C)=>Math.hypot(z.x,z.y); const arg=(z:C)=>Math.atan2(z.y,z.x); const mul=(z:C,w:C)=>({x:z.x*w.x-z.y*w.y,y:z.x*w.y+z.y*w.x});
const fmt=(z:C)=>`${z.x.toFixed(2)} ${z.y<0?"−":"+"} ${Math.abs(z.y).toFixed(2)}i`;
const argText=(z:C)=>mag(z)<1e-6?"undefined":arg(z).toFixed(2);
export default function Proof(){
 const [z,setZ]=useState<C>({x:.8,y:1}),[w,setW]=useState<C>({x:-1.2,y:.6}),[drag,setDrag]=useState<"z"|"w"|null>(null),[polar,setPolar]=useState(true),[cart,setCart]=useState(true),[circles,setCircles]=useState(true),[progress,setProgress]=useState(1),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<"idle"|"correct"|"wrong">("idle");
 const product=useMemo(()=>mul(z,w),[z,w]); const rz=mag(z),rw=mag(w),az=arg(z),aw=arg(w);
 const frame=useCallback((p:number)=>setProgress(p),[]);const anim=useRafAnimation(frame); const active=progress>=1?3:Math.min(3,Math.floor(progress*4));
 const shown=useMemo(()=>{if(progress>=1)return product;const stretch=Math.min(1,progress*2),rotate=Math.max(0,(progress-.5)*2),length=rz*(1+(rw-1)*stretch),angle=az+aw*rotate;return{x:length*Math.cos(angle),y:length*Math.sin(angle)}},[progress,product,rz,rw,az,aw]);
 const pointer=(e:React.PointerEvent<SVGSVGElement>)=>{if(!drag)return;const p=svgPoint(e,{width:W,height:H});const value={x:clamp((p.x-cx)/scale),y:clamp((cy-p.y)/scale)};if(drag==="z")setZ(value);else setW(value);setProgress(1)};
 const reset=()=>{anim.stop();setZ({x:.8,y:1});setW({x:-1.2,y:.6});setProgress(1);setPolar(true);setCart(true);setCircles(true);setFeedback("idle");setAnswer("")};
 const input=(which:"z"|"w",key:"x"|"y",value:string)=>{const n=Number(value);if(!Number.isFinite(n))return;(which==="z"?setZ:setW)(old=>({...old,[key]:clamp(n)}));setProgress(1)};
 return <PhaseOneVisualProof meta={proofConfig} activeStep={active} steps={[
  {title:"Represent the factors",body:"Each complex number is a vector with a modulus and argument."},{title:"Multiply lengths",body:<>Scale z by |w|, giving |zw| = |z||w|.</>},{title:"Add angles",body:<>Rotate by arg(w), so arg(zw)=arg(z)+arg(w).</>},{title:"Land on the product",body:"The transformed vector ends exactly at zw."}
 ]} tools={<><ToolButton title="Drag z" subtitle="Move the purple endpoint" active={drag==="z"} onClick={()=>setDrag("z")} icon={<Move size={18}/>}/><ToolButton title="Drag w" subtitle="Move the teal endpoint" active={drag==="w"} onClick={()=>setDrag("w")} icon={<Move size={18}/>}/><ToolButton title="Show polar values" subtitle="Reveal moduli and arguments" active={polar} onClick={()=>setPolar(v=>!v)} icon={<Eye size={18}/>}/><ToolButton title="Show Cartesian values" subtitle="Reveal real and imaginary parts" active={cart} onClick={()=>setCart(v=>!v)} icon={<Eye size={18}/>}/><ResetTool onClick={reset}/><ToolButton title={anim.playing?"Pause multiplication":"Animate multiplication"} subtitle="Stretch z, then rotate it" active={anim.playing} onClick={()=>{if(anim.playing)anim.stop();else{setProgress(0);anim.start(4500)}}} icon={<Play size={18}/>}/></>} result={<><h2>Multiplication = rotation + scaling</h2><p>|zw| = |z||w| and arg(zw) = arg(z) + arg(w) modulo 2π.</p></>} challenge={<><p>For the current w, how does multiplication change the magnitude of z?</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>{setAnswer("grow");setFeedback(rw>1.01?"correct":"wrong")}}>Grow</button><button onClick={()=>{setAnswer("same");setFeedback(Math.abs(rw-1)<=.01?"correct":"wrong")}}>Same size</button><button onClick={()=>{setAnswer("shrink");setFeedback(rw<.99?"correct":"wrong")}}>Shrink</button></div>{answer&&<Feedback state={feedback}/>}</>}>
  <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(70px,1fr))",gap:8,marginBottom:8}}>{([['z','x',z.x,'Re(z)'],['z','y',z.y,'Im(z)'],['w','x',w.x,'Re(w)'],['w','y',w.y,'Im(w)']] as const).map(([which,key,value,label])=><label key={label} style={{fontSize:12}}>{label}<input style={{display:"block",width:"100%",height:36,border:"1px solid #dce0ef",borderRadius:8,padding:"0 8px",marginTop:3}} type="number" step="0.1" min="-2.25" max="2.25" value={value} onChange={e=>input(which,key,e.target.value)}/></label>)}</div>
  <svg className="phaseOneCanvas" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Complex plane showing multiplication as scaling and rotation" onPointerMove={pointer} onPointerUp={()=>setDrag(null)} onPointerLeave={()=>setDrag(null)}>
   {circles&&[.5,1,1.5,2].map(q=><circle key={q} cx={cx} cy={cy} r={q*scale} fill="none" stroke="#dfe3f1" strokeDasharray="5 5"/>)}
   {Array.from({length:9},(_,i)=><g key={i}><line className="gridLine" x1={cx+(i-4)*scale/2} y1="35" x2={cx+(i-4)*scale/2} y2="525"/><line className="gridLine" x1="230" y1={cy+(i-4)*scale/2} x2="720" y2={cy+(i-4)*scale/2}/></g>)}
   <line className="axis" x1="220" y1={cy} x2="740" y2={cy}/><line className="axis" x1={cx} y1="25" x2={cx} y2="535"/><text x="744" y={cy-8}>Re</text><text x={cx+9} y="30">Im</text>
   {[{v:z,color:"#6236ed",label:"z",kind:"z" as const},{v:w,color:"#079b8e",label:"w",kind:"w" as const},{v:shown,color:"#ef8b00",label:"zw",kind:null}].map(({v,color,label,kind})=><g key={label}><defs><marker id={`arrow-${label}`} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill={color}/></marker></defs><line x1={cx} y1={cy} x2={cx+v.x*scale} y2={cy-v.y*scale} stroke={color} strokeWidth="4" markerEnd={`url(#arrow-${label})`}/><circle className={kind?"handle":""} cx={cx+v.x*scale} cy={cy-v.y*scale} r={kind?9:6} fill={color} tabIndex={kind?0:undefined} onPointerDown={kind?e=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag(kind)}:undefined}/><text x={cx+v.x*scale+12} y={cy-v.y*scale-10} fill={color} fontWeight="700">{label}{cart?` = ${fmt(kind? v:product)}`:""}</text></g>)}
   <path d={`M ${cx+58} ${cy} A 58 58 0 ${Math.abs(aw)>Math.PI?1:0} ${aw<0?1:0} ${cx+58*Math.cos(aw)} ${cy-58*Math.sin(aw)}`} fill="none" stroke="#079b8e" strokeWidth="2.5"/>
   <rect x="20" y="28" width="190" height="205" rx="14" fill="#fbfcff" stroke="#dce0ef"/><text x="38" y="56" fontWeight="700">Live complex values</text><text x="38" y="87" fill="#6236ed">z = {fmt(z)}</text><text x="38" y="112" fill="#079b8e">w = {fmt(w)}</text><text x="38" y="137" fill="#ef8b00">zw = {fmt(product)}</text>{polar&&<><text x="38" y="173">|z| = {rz.toFixed(2)}, arg z = {argText(z)}</text><text x="38" y="197">|w| = {rw.toFixed(2)}, arg w = {argText(w)}</text><text x="38" y="221">|zw| = {mag(product).toFixed(2)}, arg = {argText(product)}</text></>}
   <rect x="690" y="372" width="195" height="150" rx="14" fill="#f3f0ff" stroke="#cdc4f7"/><text x="787" y="404" textAnchor="middle" fontWeight="700" fill="#4d2bd5">Key relationships</text><text x="787" y="440" textAnchor="middle" className="mathText">|zw| = |z||w|</text><text x="787" y="466" textAnchor="middle">{mag(product).toFixed(2)} = {rz.toFixed(2)} × {rw.toFixed(2)}</text><text x="787" y="496" textAnchor="middle" className="mathText">arg(zw) = arg(z)+arg(w)</text>
  </svg>
  <div style={{display:"flex",gap:18,flexWrap:"wrap",padding:"2px 8px"}}><Toggle label="Polar values" checked={polar} onChange={setPolar}/><Toggle label="Cartesian values" checked={cart} onChange={setCart}/><Toggle label="Magnitude circles" checked={circles} onChange={setCircles}/></div>
 </PhaseOneVisualProof>
}
