"use client";

import { useState } from "react";
import { Play, ScanSearch } from "lucide-react";
import { Feedback, MathRange, PhaseOneVisualProof, ResetTool, ToolButton, useRafAnimation } from "../../../components/phase-one/PhaseOneVisualProof";
import s from "../../../components/phase-one/PhaseTwoProof.module.css";
import { formatNumber, geometricPartial } from "../../../lib/phaseTwoMath";
import { proofConfig } from "./proof.config";

export default function Proof() {
  const [r, setR] = useState(.5), [terms, setTerms] = useState(5), [selected, setSelected] = useState(0), [showAlgebra, setShowAlgebra] = useState(true);
  const [answer, setAnswer] = useState(""), [feedback, setFeedback] = useState<"idle" | "correct" | "wrong">("idle");
  const animation = useRafAnimation((progress) => setTerms(Math.max(1, Math.min(12, Math.floor(progress * 12) + 1))));
  const partial = geometricPartial(r, terms), limit = 1 / (1 - r), remainder = limit - partial;
  const colors = ["#6744df", "#079b8e", "#ed8a28", "#e65777", "#5789dc", "#ab66d5", "#36a88f", "#deaa34", "#7477c8", "#de7881", "#438b9e", "#928353"];
  const reset = () => { animation.stop(); setR(.5); setTerms(5); setSelected(0); setShowAlgebra(true); setAnswer(""); setFeedback("idle"); };
  return <PhaseOneVisualProof meta={proofConfig} activeStep={terms > 8 ? 2 : showAlgebra ? 1 : 0}
    steps={[{ title: "Tile by powers", body: "Each colored strip has height 1 and width rᵏ, so its area is rᵏ." }, { title: "Shift and subtract", body: "Sₙ − rSₙ cancels the middle terms and equals 1 − rⁿ." }, { title: "Let the tail vanish", body: "Since 0<r<1, rⁿ→0 and the strips fill area 1/(1−r)." }]}
    tools={<><ToolButton title="Animate new terms" subtitle="Add strips one by one" onClick={() => animation.playing ? animation.stop() : (setTerms(1), animation.start(4400))} active={animation.playing} icon={<Play size={18} />} /><ToolButton title="Shift-and-subtract" subtitle="Show the algebraic cancellation" onClick={() => setShowAlgebra(!showAlgebra)} active={showAlgebra} icon={<ScanSearch size={18} />} /><ResetTool onClick={reset} /></>}
    result={<><h2>1 + r + r² + ··· = 1/(1−r)</h2><p>At r = {formatNumber(r, 2)}, the limit is {formatNumber(limit)}; the current tail is {formatNumber(remainder, 4)}.</p></>}
    challenge={<><p>If r = 1/2, what is 1 + r + r² + ···?</p><div className={s.answer}><input aria-label="Geometric series challenge answer" type="number" value={answer} onChange={(e) => { setAnswer(e.target.value); setFeedback("idle"); }} /><button onClick={() => setFeedback(Number(answer) === 2 ? "correct" : "wrong")}>Check</button></div><Feedback state={feedback} /></>}>
    <div className={s.layout}><div className={s.controls}><h2>Build the sum</h2><MathRange label="Ratio r" value={r} min={.1} max={.9} step={.01} display={formatNumber(r, 2)} onChange={setR} /><MathRange label="Visible terms" value={terms} min={1} max={12} onChange={(value) => { animation.stop(); setTerms(value); setSelected(Math.min(selected, value - 1)); }} /><div className={s.mathCard}><strong>Exact values</strong><p>S<sub>{terms}</sub> = {formatNumber(partial, 5)}</p><p>Limit = {formatNumber(limit, 5)}</p><p>Unfilled tail = {formatNumber(remainder, 5)}</p></div></div><div className={s.stage}><h2>Areas 1, r, r², …</h2><div className={s.plot}><svg className="phaseOneCanvas" viewBox="0 0 680 390" role="img" aria-label={`Geometric series tiling at ratio ${r}, showing ${terms} terms`}><rect width="680" height="390" rx="14" fill="#fbfcff" /><text x="40" y="39" fontSize="15">Whole rectangle: area 1/(1−r) = {formatNumber(limit, 3)}</text><rect x="40" y="85" width="600" height="230" fill="#f4f4fa" stroke="#a5aac9" strokeWidth="2" />{Array.from({ length: terms }, (_, k) => { const start = 40 + 600 * (1 - r ** k); const width = 600 * (1 - r) * r ** k; return <g key={k} role="img" aria-label={`Term ${k + 1}: area r^${k} = ${formatNumber(r ** k, 5)}`} onClick={() => setSelected(k)} style={{ cursor: "pointer" }}><rect x={start} y="85" width={width} height="230" fill={colors[k]} fillOpacity={selected === k ? .95 : .7} stroke={selected === k ? "#1b2152" : "white"} strokeWidth={selected === k ? 3 : 1} />{width > 36 && <text x={start + width / 2} y="205" fontSize={width > 60 ? 18 : 12} textAnchor="middle" fill="white" stroke="none">{k === 0 ? "1" : k === 1 ? "r" : `r^${k}`}</text>}</g>; })}<text x="40" y="345" fontSize="13">Colored area = S{terms} = {formatNumber(partial, 4)}</text><text x="410" y="345" fontSize="13">Tail = {formatNumber(remainder, 4)}</text></svg></div><div className={s.mathCard}><strong>Selected term r<sup>{selected}</sup> = {formatNumber(r ** selected, 5)}</strong><p>Its width is r<sup>{selected}</sup> and height is 1, so area = r<sup>{selected}</sup>.</p></div>{showAlgebra && <div className={s.mathCard}><strong>Shift and subtract</strong><p>S<sub>{terms}</sub> = 1 + r + r² + ··· + r<sup>{terms - 1}</sup></p><p>rS<sub>{terms}</sub> = r + r² + ··· + r<sup>{terms}</sup></p><p>(1−r)S<sub>{terms}</sub> = 1−r<sup>{terms}</sup></p><p>S<sub>{terms}</sub> = (1−r<sup>{terms}</sup>)/(1−r) = {formatNumber(partial, 5)}</p><p>As terms → ∞, r<sup>{terms}</sup> → 0, so S → 1/(1−r).</p></div>}</div></div>
  </PhaseOneVisualProof>;
}
