"use client";
import {useCallback,useMemo,useRef,useState} from "react";
import {AreaChart,BarChart3,Eye,MoveHorizontal,Play} from "lucide-react";
import {Feedback,MathRange,PhaseOneVisualProof,ResetTool,Toggle,ToolButton,svgPoint,useRafAnimation} from "../../../components/phase-one/PhaseOneVisualProof";
import {proofConfig} from "./proof.config";
type FnKey="sin"|"linear"|"quadratic"|"cos"; type Def={label:string;f:(x:number)=>number;F:(x:number)=>number};
const defs:Record<FnKey,Def>={sin:{label:"sin x",f:Math.sin,F:x=>-Math.cos(x)},linear:{label:"x",f:x=>x,F:x=>x*x/2},quadratic:{label:"x² − 1",f:x=>x*x-1,F:x=>x*x*x/3-x},cos:{label:"cos x",f:Math.cos,F:Math.sin}};
const W=900,H=570,L=70,R=830,domain=2*Math.PI,topY=175,topScale=54,bottomY=445;
const mapX=(x:number)=>L+(x+domain)/(2*domain)*(R-L),unmapX=(x:number)=>(x-L)/(R-L)*2*domain-domain,clamp=(x:number)=>Math.max(-domain,Math.min(domain,x));
export default function Proof(){
 const [kind,setKind]=useState<FnKey>("sin"),[a,setA]=useState(-Math.PI/2),[x,setX]=useState(1.2),[showArea,setShowArea]=useState(true),[showAccum,setShowAccum]=useState(true),[riemann,setRiemann]=useState(false),[count,setCount]=useState(20),[drag,setDrag]=useState<"a"|"x"|null>(null),[progress,setProgress]=useState(0),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<"idle"|"correct"|"wrong">("idle"); const startRef=useRef(a),destRef=useRef(x);
 const def=defs[kind],area=def.F(x)-def.F(a),fx=def.f(x);
 const trend=fx>1e-8?"increase":fx<-1e-8?"decrease":"stay locally flat";
 const maxAccum=useMemo(()=>Math.max(1,...Array.from({length:161},(_,i)=>Math.abs(def.F(-domain+i*2*domain/160)-def.F(a)))),[def,a]); const aScale=90/maxAccum;
 const curve=useMemo(()=>Array.from({length:241},(_,i)=>{const q=-domain+i*2*domain/240;const val=Math.max(-2.7,Math.min(2.7,def.f(q)));return `${i?"L":"M"} ${mapX(q)} ${topY-val*topScale}`}).join(" "),[def]);
 const accumPath=useMemo(()=>Array.from({length:241},(_,i)=>{const q=-domain+i*2*domain/240;return `${i?"L":"M"} ${mapX(q)} ${bottomY-(def.F(q)-def.F(a))*aScale}`}).join(" "),[def,a,aScale]);
 const frame=useCallback((p:number)=>{setProgress(p);setX(startRef.current+(destRef.current-startRef.current)*p)},[]),anim=useRafAnimation(frame); const active=Math.min(3,Math.floor(progress*4));
 const pointer=(e:React.PointerEvent<SVGSVGElement>)=>{if(!drag)return;const p=svgPoint(e,{width:W,height:H}),v=clamp(unmapX(p.x));if(drag==="a")setA(v);else setX(v)};
 const reset=()=>{anim.stop();setKind("sin");setA(-Math.PI/2);setX(1.2);setShowArea(true);setShowAccum(true);setRiemann(false);setCount(20);setProgress(0);setAnswer("");setFeedback("idle")};
 const lo=Math.min(a,x),hi=Math.max(a,x),strips=riemann?count:90,dx=(hi-lo)/strips;
 return <PhaseOneVisualProof meta={proofConfig} activeStep={active} steps={[
  {title:"Fix a starting bound",body:"The lower bound a anchors the accumulation."},{title:"Sweep the upper bound",body:<>A(x) totals signed area from a to x.</>},{title:"Add and subtract",body:"Area above the axis adds; area below subtracts."},{title:"Link area to slope",body:<>As x moves, A′(x)=f(x).</>}
 ]} tools={<><ToolButton title="Move upper bound x" subtitle="Drag the green point or use the slider" active={drag==="x"} onClick={()=>setDrag("x")} icon={<MoveHorizontal size={18}/>}/><ToolButton title="Show signed area" subtitle="Blue adds and red subtracts" active={showArea} onClick={()=>setShowArea(v=>!v)} icon={<AreaChart size={18}/>}/><ToolButton title="Show accumulation graph" subtitle="Display A(x) below f(x)" active={showAccum} onClick={()=>setShowAccum(v=>!v)} icon={<Eye size={18}/>}/><ToolButton title="Show Riemann rectangles" subtitle={`Use ${count} midpoint rectangles`} active={riemann} onClick={()=>setRiemann(v=>!v)} icon={<BarChart3 size={18}/>}/><ResetTool onClick={reset}/><ToolButton title={anim.playing?"Pause sweep":"Animate sweep"} subtitle="Accumulate from a to the selected x" active={anim.playing} onClick={()=>{if(anim.playing)anim.stop();else{startRef.current=a;destRef.current=x;setX(a);setProgress(0);anim.start(4800)}}} icon={<Play size={18}/>}/></>} result={<><h2>Integral = accumulated signed area</h2><p>A(x) = ∫ₐˣ f(t)dt, and its instantaneous rate of change is A′(x)=f(x).</p></>} challenge={<><p>At the current x, f(x) ≈ {Math.abs(fx)<1e-8?"0":fx.toFixed(3)}. As x moves right, A(x) should {trend}.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>{setAnswer("increase");setFeedback(trend==="increase"?"correct":"wrong")}}>Increase</button><button onClick={()=>{setAnswer("flat");setFeedback(trend==="stay locally flat"?"correct":"wrong")}}>Stay flat</button><button onClick={()=>{setAnswer("decrease");setFeedback(trend==="decrease"?"correct":"wrong")}}>Decrease</button></div>{answer&&<Feedback state={feedback}/>}</>}>
  <div style={{display:"grid",gridTemplateColumns:"170px 1fr 1fr",gap:9}}><label style={{border:"1px solid #e0e3f0",borderRadius:12,padding:10,fontSize:12}}>Function<select value={kind} onChange={e=>setKind(e.target.value as FnKey)} style={{display:"block",width:"100%",height:34,marginTop:6,border:"1px solid #dce0ef",borderRadius:8}}>{Object.entries(defs).map(([key,d])=><option value={key} key={key}>f(x) = {d.label}</option>)}</select></label><MathRange label="Lower bound a" value={a} min={-domain} max={domain} step={.01} onChange={setA} display={(a/Math.PI).toFixed(2)+"π"}/><MathRange label="Upper bound x" value={x} min={-domain} max={domain} step={.01} onChange={setX} display={(x/Math.PI).toFixed(2)+"π"}/></div>
  {riemann&&<div style={{marginTop:7}}><MathRange label="Rectangle count n" value={count} min={4} max={80} step={1} onChange={setCount}/></div>}
  <svg className="phaseOneCanvas" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Function and accumulated signed area graph" onPointerMove={pointer} onPointerUp={()=>setDrag(null)} onPointerLeave={()=>setDrag(null)}>
   {[topY,bottomY].map(base=><g key={base}>{[0,.25,.5,.75,1].map(q=><line key={q} className="gridLine" x1={L+q*(R-L)} y1={base-105} x2={L+q*(R-L)} y2={base+105}/>)}<line className="axis" x1={L-10} y1={base} x2={R+12} y2={base}/><line className="axis" x1={mapX(0)} y1={base-115} x2={mapX(0)} y2={base+112}/></g>)}
   {showArea&&dx>0&&Array.from({length:strips},(_,i)=>{const q=lo+(i+.5)*dx,v=def.f(q),w=Math.max(.5,mapX(lo+dx)-mapX(lo));return <rect key={i} x={mapX(lo+i*dx)} y={Math.min(topY,topY-v*topScale)} width={w+.4} height={Math.abs(v)*topScale} fill={v>=0?"rgba(80,105,230,.25)":"rgba(239,72,72,.22)"} stroke={riemann?(v>=0?"#5368df":"#e94c4c"):"none"} strokeWidth=".7"/>})}
   <path d={curve} fill="none" stroke="#6537f0" strokeWidth="3.5"/><text x="82" y="48" fontWeight="700">f(x) = {def.label}</text><text x="82" y="70" fill="#58638f">Blue area adds · red area subtracts</text>
   <line x1={mapX(a)} y1={topY} x2={mapX(a)} y2={topY-def.f(a)*topScale} stroke="#6236ed" strokeWidth="2" strokeDasharray="5 4"/><circle className="purple handle" cx={mapX(a)} cy={topY} r="8" tabIndex={0} aria-label="lower bound a" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag("a")}}/><text x={mapX(a)} y={topY+22} textAnchor="middle" fill="#6236ed">a</text>
   <line x1={mapX(x)} y1={topY} x2={mapX(x)} y2={topY-fx*topScale} stroke="#079b62" strokeWidth="2.5" strokeDasharray="5 4"/><circle cx={mapX(x)} cy={topY-fx*topScale} r="8" fill="#079b62" stroke="#fff" strokeWidth="3"/><circle className="green handle" cx={mapX(x)} cy={topY} r="8" tabIndex={0} aria-label="upper bound x" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag("x")}}/><text x={mapX(x)} y={topY+22} textAnchor="middle" fill="#07865b">x</text>
   {showAccum&&<><path d={accumPath} fill="none" stroke="#6537f0" strokeWidth="3.5"/><line x1={mapX(x)} y1={bottomY} x2={mapX(x)} y2={bottomY-area*aScale} stroke="#079b62" strokeWidth="2" strokeDasharray="5 4"/><circle cx={mapX(x)} cy={bottomY-area*aScale} r="8" fill="#079b62" stroke="#fff" strokeWidth="3"/><text x={mapX(x)+12} y={bottomY-area*aScale-10} fill="#07865b">A(x)={area.toFixed(3)}</text></>}
   <text x="82" y="330" fontWeight="700">Accumulation function A(x) = ∫ₐˣ f(t)dt</text><rect x="650" y="310" width="225" height="95" rx="13" fill="#f3f0ff" stroke="#cfc6f8"/><text x="762" y="340" textAnchor="middle" fontWeight="700" fill="#4d2bd5">Accumulated area</text><text x="762" y="371" textAnchor="middle" className="mathText">A(x) = {area.toFixed(4)}</text><text x="762" y="394" textAnchor="middle">A′(x) = f(x) = {fx.toFixed(4)}</text>
  </svg>
  <div style={{display:"flex",gap:18,flexWrap:"wrap",padding:"2px 8px"}}><Toggle label="Signed area" checked={showArea} onChange={setShowArea}/><Toggle label="Accumulation graph" checked={showAccum} onChange={setShowAccum}/><Toggle label="Riemann rectangles" checked={riemann} onChange={setRiemann}/></div>
 </PhaseOneVisualProof>
}
