"use client";
import {useCallback,useMemo,useRef,useState} from "react";
import {Eye,MoveHorizontal,Play,TrendingUp} from "lucide-react";
import {Feedback,MathRange,PhaseOneVisualProof,ResetTool,Toggle,ToolButton,svgPoint,useRafAnimation} from "../../../components/phase-one/PhaseOneVisualProof";
import {proofConfig} from "./proof.config";
type FnKey="square"|"cube"|"sin"|"exp"; const defs:Record<FnKey,{label:string;f:(x:number)=>number;d:(x:number)=>number;domain:[number,number]}>= {square:{label:"x²",f:x=>x*x,d:x=>2*x,domain:[-2.4,2.4]},cube:{label:"x³",f:x=>x*x*x,d:x=>3*x*x,domain:[-1.75,1.75]},sin:{label:"sin x",f:Math.sin,d:Math.cos,domain:[-3.2,3.2]},exp:{label:"eˣ",f:Math.exp,d:Math.exp,domain:[-2.8,1.7]}};
const W=900,H=560,ox=455,oy=310,sx=105,sy=58,clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export default function Proof(){
 const [kind,setKind]=useState<FnKey>("square"),[x,setX]=useState(1),[h,setHState]=useState(.5),[secant,setSecant]=useState(true),[tangent,setTangent]=useState(true),[delta,setDelta]=useState(true),[drag,setDrag]=useState(false),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<"idle"|"correct"|"wrong">("idle"),[progress,setProgress]=useState(0); const startH=useRef(.5);
 const def=defs[kind],y=def.f(x),x2=x+h,y2=def.f(x2),slope=(y2-y)/h,derivative=def.d(x);
 const setH=(v:number)=>setHState(Math.abs(v)<.02?(v<0?-.02:.02):v);
 const curve=useMemo(()=>Array.from({length:181},(_,i)=>{const q=def.domain[0]+i*(def.domain[1]-def.domain[0])/180;return `${i?"L":"M"} ${ox+q*sx} ${oy-clamp(def.f(q),-4.3,4.3)*sy}`}).join(" "),[def]);
 const frame=useCallback((p:number)=>{setProgress(p);setHState(Math.sign(startH.current||1)*Math.max(.02,Math.abs(startH.current)*(1-p)))},[]),anim=useRafAnimation(frame); const active=Math.min(3,Math.floor(progress*4));
 const changeFn=(v:FnKey)=>{setKind(v);const d=defs[v];setX(q=>clamp(q,d.domain[0]+.7,d.domain[1]-.7));setH(.5);setProgress(0)};
 const pointer=(e:React.PointerEvent<SVGSVGElement>)=>{if(!drag)return;const p=svgPoint(e,{width:W,height:H});setX(clamp((p.x-ox)/sx,def.domain[0]+.7,def.domain[1]-.7))};
 const line=(m:number,bx:number,by:number,color:string)=>{const xa=-3.4,xb=3.4;return <line x1={ox+xa*sx} y1={oy-(by+m*(xa-bx))*sy} x2={ox+xb*sx} y2={oy-(by+m*(xb-bx))*sy} stroke={color} strokeWidth="3"/>};
 const reset=()=>{anim.stop();setKind("square");setX(1);setH(.5);setSecant(true);setTangent(true);setDelta(true);setProgress(0);setAnswer("");setFeedback("idle")};
 return <PhaseOneVisualProof meta={proofConfig} activeStep={active} steps={[
  {title:"Choose two points",body:"A is at x and B is at x+h on the curve."},{title:"Measure average change",body:<>The secant slope is Δy/Δx.</>},{title:"Let h approach zero",body:"B moves toward A without ever dividing by zero."},{title:"Reach instantaneous slope",body:<>The secant converges to the tangent with slope f′(x).</>}
 ]} tools={<><ToolButton title="Move point x" subtitle="Drag A or use the x slider" active={drag} onClick={()=>setDrag(v=>!v)} icon={<TrendingUp size={18}/>}/><ToolButton title="Advance h" subtitle="Step h by 0.1, or use its slider" onClick={()=>{anim.stop();setH(h>=.9?-1:h+.1)}} icon={<MoveHorizontal size={18}/>}/><ToolButton title="Show secant" subtitle="Line through A and B" active={secant} onClick={()=>setSecant(v=>!v)} icon={<Eye size={18}/>}/><ToolButton title="Show tangent" subtitle="Instantaneous slope at A" active={tangent} onClick={()=>setTangent(v=>!v)} icon={<Eye size={18}/>}/><ResetTool onClick={reset}/><ToolButton title={anim.playing?"Pause limit":"Animate limit"} subtitle="Watch h approach zero" active={anim.playing} onClick={()=>{if(anim.playing)anim.stop();else{const replayH=Math.abs(h)<=.03?.8:h;startH.current=replayH;setHState(replayH);setProgress(0);anim.start(4300)}}} icon={<Play size={18}/>}/></>} result={<><h2>Derivative = instantaneous slope</h2><p>f′(x) = lim h→0 [f(x+h) − f(x)] / h, evaluated without ever setting h to zero.</p></>} challenge={<><p>For f(x)=x² at x=2, predict the tangent slope.</p><div style={{display:"flex",gap:8}}><input value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback("idle")}} inputMode="decimal" aria-label="tangent slope answer"/><button onClick={()=>setFeedback(Number(answer)===4?"correct":"wrong")}>Check</button></div><Feedback state={feedback}/></>}>
  <div style={{display:"grid",gridTemplateColumns:"180px 1fr 1fr",gap:9,alignItems:"stretch"}}><label style={{border:"1px solid #e0e3f0",borderRadius:12,padding:10,fontSize:12}}>Function<select value={kind} onChange={e=>changeFn(e.target.value as FnKey)} style={{display:"block",width:"100%",height:34,marginTop:6,border:"1px solid #dce0ef",borderRadius:8}}>{Object.entries(defs).map(([key,d])=><option key={key} value={key}>f(x) = {d.label}</option>)}</select></label><MathRange label="Point x" value={x} min={def.domain[0]+.7} max={def.domain[1]-.7} step={.01} onChange={setX} display={x.toFixed(2)}/><MathRange label="Step h" value={h} min={-1} max={1} step={.01} onChange={setH} display={h.toFixed(3)}/></div>
  <svg className="phaseOneCanvas" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Secant line converging to a tangent" onPointerMove={pointer} onPointerUp={()=>setDrag(false)} onPointerLeave={()=>setDrag(false)}>
   {Array.from({length:15},(_,i)=><g key={i}><line className="gridLine" x1={ox+(i-7)*sx/2} y1="30" x2={ox+(i-7)*sx/2} y2="520"/><line className="gridLine" x1="65" y1={oy+(i-7)*sy/2} x2="835" y2={oy+(i-7)*sy/2}/></g>)}<line className="axis" x1="55" y1={oy} x2="850" y2={oy}/><line className="axis" x1={ox} y1="25" x2={ox} y2="530"/><path d={curve} fill="none" stroke="#6537f0" strokeWidth="4"/>
   {secant&&line(slope,x,y,"#176bd7")}{tangent&&line(derivative,x,y,"#08a05c")}
   {delta&&<><line x1={ox+x*sx} y1={oy-y*sy} x2={ox+x2*sx} y2={oy-y*sy} stroke="#ef5038" strokeDasharray="6 4" strokeWidth="2"/><line x1={ox+x2*sx} y1={oy-y*sy} x2={ox+x2*sx} y2={oy-y2*sy} stroke="#ef5038" strokeDasharray="6 4" strokeWidth="2"/><text x={ox+(x+x2)/2*sx} y={oy-y*sy+24} fill="#df3e2c">Δx={h.toFixed(2)}</text><text x={ox+x2*sx+9} y={oy-(y+y2)/2*sy} fill="#df3e2c">Δy={(y2-y).toFixed(2)}</text></>}
   <circle className="purple handle" cx={ox+x*sx} cy={oy-y*sy} r="10" tabIndex={0} role="slider" aria-label="point x" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDrag(true)}}/><circle cx={ox+x2*sx} cy={oy-y2*sy} r="9" fill="#176bd7" stroke="#fff" strokeWidth="3"/><text x={ox+x*sx-14} y={oy-y*sy-17} textAnchor="end" fill="#6537f0">A ({x.toFixed(2)}, {y.toFixed(2)})</text><text x={ox+x2*sx+12} y={oy-y2*sy-15} fill="#176bd7">B ({x2.toFixed(2)}, {y2.toFixed(2)})</text>
   <rect x="20" y="38" width="230" height="175" rx="14" fill="#fbfcff" stroke="#dce0ef"/><text x="38" y="70" fontWeight="700">Live slope calculation</text><text x="38" y="101">f(x) = {y.toFixed(3)}</text><text x="38" y="126">f(x+h) = {y2.toFixed(3)}</text><text x="38" y="158" className="mathText">[f(x+h)−f(x)] / h</text><text x="38" y="184" fill="#176bd7" fontWeight="700">secant slope = {slope.toFixed(4)}</text><text x="38" y="207" fill="#079557" fontWeight="700">f′(x) = {derivative.toFixed(4)}</text>
  </svg>
  <div style={{display:"flex",gap:18,flexWrap:"wrap",padding:"2px 8px"}}><Toggle label="Secant line" checked={secant} onChange={setSecant}/><Toggle label="Tangent line" checked={tangent} onChange={setTangent}/><Toggle label="Δx and Δy" checked={delta} onChange={setDelta}/></div>
 </PhaseOneVisualProof>
}
